#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: d48e422
#
# Source0 file verified with key 0xA48E86DB0B830498 (av1-discuss@aomedia.org)
#
Name     : libaom
Version  : 3.9.1
Release  : 3
URL      : https://storage.googleapis.com/aom-releases/libaom-3.9.1.tar.gz
Source0  : https://storage.googleapis.com/aom-releases/libaom-3.9.1.tar.gz
Source1  : https://storage.googleapis.com/aom-releases/libaom-3.9.1.tar.gz.asc
Source2  : A48E86DB0B830498.pkey
Summary  : GoogleMock (without main() function)
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause BSD-3-Clause-Clear HPND MIT
Requires: libaom-bin = %{version}-%{release}
Requires: libaom-lib = %{version}-%{release}
Requires: libaom-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : nasm
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : python3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=========
# AV1 Codec Library
## Contents
1. [Building the lib and applications](#building-the-library-and-applications)
- [Prerequisites](#prerequisites)
- [Get the code](#get-the-code)
- [Basics](#basic-build)
- [Configuration options](#configuration-options)
- [Dylib builds](#dylib-builds)
- [Debugging](#debugging)
- [Cross compiling](#cross-compiling)
- [Sanitizer support](#sanitizers)
- [MSVC builds](#microsoft-visual-studio-builds)
- [Xcode builds](#xcode-builds)
- [Emscripten builds](#emscripten-builds)
- [Extra Build Flags](#extra-build-flags)
- [Build with VMAF support](#build-with-vmaf)
2. [Testing the library](#testing-the-av1-codec)
- [Basics](#testing-basics)
- [Unit tests](#unit-tests)
- [Example tests](#example-tests)
- [Encoder tests](#encoder-tests)
- [IDE hosted tests](#ide-hosted-tests)
- [Downloading test data](#downloading-the-test-data)
- [Adding a new test data file](#adding-a-new-test-data-file)
- [Additional test data](#additional-test-data)
- [Sharded testing](#sharded-testing)
- [Running tests directly](#running-test_libaom-directly)
- [Running tests via CMake](#running-the-tests-via-the-cmake-build)
3. [Coding style](#coding-style)
4. [Submitting patches](#submitting-patches)
- [Login cookie](#login-cookie)
- [Contributor agreement](#contributor-agreement)
- [Testing your code](#testing-your-code)
- [Commit message hook](#commit-message-hook)
- [Upload your change](#upload-your-change)
- [Incorporating Reviewer Comments](#incorporating-reviewer-comments)
- [Submitting your change](#submitting-your-change)
- [Viewing change status](#viewing-the-status-of-uploaded-changes)
5. [Support](#support)
6. [Bug reports](#bug-reports)

%package bin
Summary: bin components for the libaom package.
Group: Binaries
Requires: libaom-license = %{version}-%{release}

%description bin
bin components for the libaom package.


%package dev
Summary: dev components for the libaom package.
Group: Development
Requires: libaom-lib = %{version}-%{release}
Requires: libaom-bin = %{version}-%{release}
Provides: libaom-devel = %{version}-%{release}
Requires: libaom = %{version}-%{release}

%description dev
dev components for the libaom package.


%package lib
Summary: lib components for the libaom package.
Group: Libraries
Requires: libaom-license = %{version}-%{release}

%description lib
lib components for the libaom package.


%package license
Summary: license components for the libaom package.
Group: Default

%description license
license components for the libaom package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) A48E86DB0B830498' gpg.status
%setup -q -n libaom-3.9.1
cd %{_builddir}/libaom-3.9.1
pushd ..
cp -a libaom-3.9.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723502594
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1723502594
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libaom
cp %{_builddir}/libaom-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libaom/c338c1059653be6283c407cd673147612b69eed7 || :
cp %{_builddir}/libaom-%{version}/third_party/SVT-AV1/LICENSE.md %{buildroot}/usr/share/package-licenses/libaom/46e7694aaf9130a640379739ddc0b972f98a7230 || :
cp %{_builddir}/libaom-%{version}/third_party/fastfeat/LICENSE %{buildroot}/usr/share/package-licenses/libaom/7cbe19df00ff13a33eb7638354c37c4f7382f94f || :
cp %{_builddir}/libaom-%{version}/third_party/googletest/src/LICENSE %{buildroot}/usr/share/package-licenses/libaom/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/libaom-%{version}/third_party/libwebm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/libaom/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9 || :
cp %{_builddir}/libaom-%{version}/third_party/libyuv/LICENSE %{buildroot}/usr/share/package-licenses/libaom/f71908f9aaa4aee0f15f9983b6cf83791d18cfd7 || :
cp %{_builddir}/libaom-%{version}/third_party/vector/LICENSE %{buildroot}/usr/share/package-licenses/libaom/3c299a3e18e5713f612e1247d49d100bc477b0f2 || :
cp %{_builddir}/libaom-%{version}/third_party/x86inc/LICENSE %{buildroot}/usr/share/package-licenses/libaom/697c7d5a9839cf4160acd85431b0c58be874dba8 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/aomdec
/V3/usr/bin/aomenc
/usr/bin/aomdec
/usr/bin/aomenc

%files dev
%defattr(-,root,root,-)
/usr/include/aom/aom.h
/usr/include/aom/aom_codec.h
/usr/include/aom/aom_decoder.h
/usr/include/aom/aom_encoder.h
/usr/include/aom/aom_external_partition.h
/usr/include/aom/aom_frame_buffer.h
/usr/include/aom/aom_image.h
/usr/include/aom/aom_integer.h
/usr/include/aom/aomcx.h
/usr/include/aom/aomdx.h
/usr/lib64/libaom.so
/usr/lib64/pkgconfig/aom.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libaom.so.3.9.1
/usr/lib64/libaom.so.3
/usr/lib64/libaom.so.3.9.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libaom/3c299a3e18e5713f612e1247d49d100bc477b0f2
/usr/share/package-licenses/libaom/46e7694aaf9130a640379739ddc0b972f98a7230
/usr/share/package-licenses/libaom/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9
/usr/share/package-licenses/libaom/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/libaom/697c7d5a9839cf4160acd85431b0c58be874dba8
/usr/share/package-licenses/libaom/7cbe19df00ff13a33eb7638354c37c4f7382f94f
/usr/share/package-licenses/libaom/c338c1059653be6283c407cd673147612b69eed7
/usr/share/package-licenses/libaom/f71908f9aaa4aee0f15f9983b6cf83791d18cfd7
